# Hostname (and path) to the root
baseurl: "https://docs.zymbit.com"

# General site configuration
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
languageCode: "en-US"
paginate: 7
rssLimit: 10

theme:
  - docsy

outputs:
  home:
    - HTML
  section:
    - HTML
    - SITEMAP

outputFormats:
  SITEMAP:
    mediaType: application/xml
    baseName: sitemap
    isHTML: false
    isPlainText: true
    noUgly: true
    rel: sitemap

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 4
  goldmark:
    extensions:
      linkify: false
      table: true
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: monokai
    tabWidth: 4

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

taxonomies:
  category: categories
  tag: tags

permalinks:
  docs: "/:sections/:slug/"

# Because this is primarily a docs site, we want all of our pages to use the
# docs formatting. Normally, the layout is chosen by the name of the first
# directory under `content/`. Since we don't want to have to put `type: docs`
# in every page or have to put the entire site within a `content/docs/` directory,
# we can define cascading frontmatter that causes every page below this to
# inherit `type: docs`
#
# Any other key-value pairs added under the `cascade` key will be inherited by
# every other site page. More information about front matter cascades:
# https://gohugo.io/content-management/front-matter#front-matter-cascade
cascade:
  type: docs
